### ISSUE TITLE
Plugin breaks localstack

### ISSUE THREAD

**Issue by bdrozd-tsh** [DataDog/serverless-plugin-datadog#155]
Hello guys, first of all, thank you for your contribution and effort put into this plugin. I am aware that this might be localstack issue but wanted to point it here first. Sorry if that is inconvenient for you.

## Expected Behavior

`serverless-plugin-datadog` plugin doesn't break localstack environment. Invoking lambda functions works

## Actual Behavior

`serverless-plugin-datadog` breaks localstack environment. Basically, it is impossible to invoke a single lambda function

## Steps to Reproduce the Problem

  1. setup minimalistic sls project (in my case the project was based on template `aws-nodejs-ecma-script`)
  1. add `serverless-plugin-datadog` plugin
  1. add localstack setup (in my case the setup was provided via docker-compose)
  2. start localstack via `docker-compose up`
  3. deploy the sls stack to localstack
  4. invoke a single lambda function, e.g. `aws --endpoint-url=http://localhost:4566 lambda invoke --function-name some-fx-name output`

## Specifications

  - Serverless Framework version: Framework Core: 2.52.1, Plugin: 5.4.3, SDK: 4.2.5, Components: 3.14.0
  - Datadog Serverless Plugin version: 2.27.0 
  - Lambda function runtime (Python 3.7, Node 10, etc.): Node 14
  
## Stacktrace
  
  ```
my-service | 2021-08-10T09:25:48:INFO:localstack.services.awslambda.lambda_api: Error executing Lambda function arn:aws:lambda:eu-west-1:000000000000:function:some-fx-name-1: Lambda process returned with error. Result: {"errorType":"Runtime.ImportModuleError","errorMessage":"Error: Cannot find module 'handler'\nRequire stack:\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js"}. Output:
my-service | 2021-08-10T09:25:48.181Z	undefined	ERROR	Uncaught Exception 	{"errorType":"Runtime.ImportModuleError","errorMessage":"Error: Cannot find module 'handler'\nRequire stack:\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js","stack":["Runtime.ImportModuleError: Error: Cannot find module 'handler'","Require stack:","- /var/runtime/UserFunction.js","- /var/runtime/index.js","    at _loadUserApp (/var/runtime/UserFunction.js:100:13)","    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)","    at Object.<anonymous> (/var/runtime/index.js:43:30)","    at Module._compile (internal/modules/cjs/loader.js:1063:30)","    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)","    at Module.load (internal/modules/cjs/loader.js:928:32)","    at Function.Module._load (internal/modules/cjs/loader.js:769:14)","    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)","    at internal/main/run_main_module.js:17:47"]}
my-service | START RequestId: b7b9b195-b8f8-10ac-4baf-d3cc4ad1c0fa Version: $LATEST
my-service | END RequestId: b7b9b195-b8f8-10ac-4baf-d3cc4ad1c0fa
my-service | REPORT RequestId: b7b9b195-b8f8-10ac-4baf-d3cc4ad1c0fa	Init Duration: 173.34 ms	Duration: 1.56 ms	Billed Duration: 100 ms	Memory Size: 1536 MB	Max Memory Used: 41 MB	 Traceback (most recent call last):
my-service |   File "/opt/code/localstack/localstack/utils/docker.py", line 335, in _run_async_cmd
my-service |     stderr,
my-service | subprocess.CalledProcessError: Command '['docker', 'start', '--interactive', '--attach', 'b45d10cc7f07af5292cc42a84e4111276503ac3542eb3958a0231f48c5a27aa8']' returned non-zero exit status 1.
my-service |
my-service | During handling of the above exception, another exception occurred:
my-service |
my-service | Traceback (most recent call last):
my-service |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 358, in run_lambda_executor
my-service |     func_details, env_vars, command, docker_flags=docker_flags, stdin=event_stdin_bytes
my-service |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 852, in execute_in_container
my-service |     container_id, interactive=not background, attach=not background, stdin=stdin
my-service |   File "/opt/code/localstack/localstack/utils/docker.py", line 314, in start_container
my-service |     return self._run_async_cmd(cmd, stdin, container_name_or_id)
my-service |   File "/opt/code/localstack/localstack/utils/docker.py", line 346, in _run_async_cmd
my-service |     "Docker process returned with errorcode %s" % e.returncode, e.stdout, e.stderr
my-service | localstack.utils.docker.ContainerException: ('Docker process returned with errorcode 1', b'\n{"errorType":"Runtime.ImportModuleError","errorMessage":"Error: Cannot find module \'handler\'\\nRequire stack:\\n- /var/runtime/UserFunction.js\\n- /var/runtime/index.js"}\n', b'2021-08-10T09:25:48.181Z\tundefined\tERROR\tUncaught Exception \t{"errorType":"Runtime.ImportModuleError","errorMessage":"Error: Cannot find module \'handler\'\\nRequire stack:\\n- /var/runtime/UserFunction.js\\n- /var/runtime/index.js","stack":["Runtime.ImportModuleError: Error: Cannot find module \'handler\'","Require stack:","- /var/runtime/UserFunction.js","- /var/runtime/index.js","    at _loadUserApp (/var/runtime/UserFunction.js:100:13)","    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)","    at Object.<anonymous> (/var/runtime/index.js:43:30)","    at Module._compile (internal/modules/cjs/loader.js:1063:30)","    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)","    at Module.load (internal/modules/cjs/loader.js:928:32)","    at Function.Module._load (internal/modules/cjs/loader.js:769:14)","    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)","    at internal/main/run_main_module.js:17:47"]}\n\x1b[32mSTART RequestId: b7b9b195-b8f8-10ac-4baf-d3cc4ad1c0fa Version: $LATEST\x1b[0m\n\x1b[32mEND RequestId: b7b9b195-b8f8-10ac-4baf-d3cc4ad1c0fa\x1b[0m\n\x1b[32mREPORT RequestId: b7b9b195-b8f8-10ac-4baf-d3cc4ad1c0fa\tInit Duration: 173.34 ms\tDuration: 1.56 ms\tBilled Duration: 100 ms\tMemory Size: 1536 MB\tMax Memory Used: 41 MB\t\x1b[0m\n')
my-service |
my-service | The above exception was the direct cause of the following exception:
my-service |
my-service | Traceback (most recent call last):
my-service |   File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 752, in run_lambda
my-service |     lock_discriminator=lock_discriminator,
my-service |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 279, in execute
my-service |     return do_execute()
my-service |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 269, in do_execute
my-service |     return _run(func_arn=func_arn)
my-service |   File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 157, in wrapped
my-service |     raise e
my-service |   File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 153, in wrapped
my-service |     result = func(*args, **kwargs)
my-service |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 256, in _run
my-service |     raise e
my-service |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 242, in _run
my-service |     result = self._execute(func_arn, func_details, event, context, version)
my-service |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 507, in _execute
my-service |     event=stdin, env_vars=environment, func_details=func_details, docker_flags=docker_flags
my-service |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 397, in run_lambda_executor
my-service |     ) from error
my-service | localstack.services.awslambda.lambda_executors.InvocationException: Lambda process returned with error. Result: {"errorType":"Runtime.ImportModuleError","errorMessage":"Error: Cannot find module 'handler'\nRequire stack:\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js"}. Output:
my-service | 2021-08-10T09:25:48.181Z	undefined	ERROR	Uncaught Exception 	{"errorType":"Runtime.ImportModuleError","errorMessage":"Error: Cannot find module 'handler'\nRequire stack:\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js","stack":["Runtime.ImportModuleError: Error: Cannot find module 'handler'","Require stack:","- /var/runtime/UserFunction.js","- /var/runtime/index.js","    at _loadUserApp (/var/runtime/UserFunction.js:100:13)","    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)","    at Object.<anonymous> (/var/runtime/index.js:43:30)","    at Module._compile (internal/modules/cjs/loader.js:1063:30)","    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)","    at Module.load (internal/modules/cjs/loader.js:928:32)","    at Function.Module._load (internal/modules/cjs/loader.js:769:14)","    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)","    at internal/main/run_main_module.js:17:47"]}
my-service | START RequestId: b7b9b195-b8f8-10ac-4baf-d3cc4ad1c0fa Version: $LATEST
my-service | END RequestId: b7b9b195-b8f8-10ac-4baf-d3cc4ad1c0fa
my-service | REPORT RequestId: b7b9b195-b8f8-10ac-4baf-d3cc4ad1c0fa	Init Duration: 173.34 ms	Duration: 1.56 ms	Billed Duration: 100 ms	Memory Size: 1536 MB	Max Memory Used: 41 MB

  ```

**Comment by astuyve** [comment]
Hi @bdrozd-tsh - Thanks for reaching out!
Can you share the `datadog` config block from your `serverless.yml` file?
Can you confirm that removing the plugin fixes this?

You might consider wrapping the datadog plugin in a conditional, so that it won't be used for certain stages (like your localstack stage, for example.)

**Comment by astuyve** [comment]
Closing this as stale, since it's been over 30 days with no response. Please feel free to re-open this ticket if needed. Thanks!
