### ISSUE TITLE
Cannot find module 'axios'

### ISSUE THREAD

**Issue by gs11** [DataDog/serverless-plugin-datadog#223]
## Expected Behavior

`sls package` successfully builds a package

## Actual Behavior

Fails with `Cannot find module 'axios'`.
After manually installing it, it then fails with not finding `form-data`

## Steps to Reproduce the Problem

  1. Add `"serverless-plugin-datadog": "^3.5.2",` as a dev dependency to your sls service
  1. Run `npm install`
  1. Run `sls package`

## Specifications

  - Serverless Framework version: 
Framework Core: 2.66.2
Plugin: 5.5.1
SDK: 4.3.0
Components: 3.18.1
  - Datadog Serverless Plugin version: 3.5.2
  - Lambda function runtime (Python 3.7, Node 10, etc.): v16.13.0
  
## Stacktrace
``` Error ---------------------------------------------------

  Error: Cannot find module 'axios'
  Require stack:
  - /redacted-my-service/node_modules/serverless-plugin-datadog/dist/src/helpers/apikey.js
  - /redacted-my-service/node_modules/serverless-plugin-datadog/dist/src/source-code-integration.js
  - /redacted-my-service/node_modules/serverless-plugin-datadog/dist/src/index.js
  - /home/gs/.nvm/versions/node/v16.13.0/lib/node_modules/serverless/lib/classes/PluginManager.js
  - /home/gs/.nvm/versions/node/v16.13.0/lib/node_modules/serverless/lib/Serverless.js
  - /home/gs/.nvm/versions/node/v16.13.0/lib/node_modules/serverless/scripts/serverless.js
  - /home/gs/.nvm/versions/node/v16.13.0/lib/node_modules/serverless/bin/serverless.js
      at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
      at Function.Module._load (node:internal/modules/cjs/loader:778:27)
      at Module.require (node:internal/modules/cjs/loader:1005:19)
      at require (node:internal/modules/cjs/helpers:102:18)
      at Object.<anonymous> (/redacted-my-service/node_modules/serverless-plugin-datadog/dist/src/helpers/apikey.js:16:33)
      at Module._compile (node:internal/modules/cjs/loader:1101:14)
      at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
      at Module.load (node:internal/modules/cjs/loader:981:32)
      at Function.Module._load (node:internal/modules/cjs/loader:822:12)
      at Module.require (node:internal/modules/cjs/loader:1005:19)
      at require (node:internal/modules/cjs/helpers:102:18)
      at Object.<anonymous> (/redacted-my-service/node_modules/serverless-plugin-datadog/dist/src/source-code-integration.js:15:18)
      at Module._compile (node:internal/modules/cjs/loader:1101:14)
      at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
      at Module.load (node:internal/modules/cjs/loader:981:32)
      at Function.Module._load (node:internal/modules/cjs/loader:822:12)
      at Module.require (node:internal/modules/cjs/loader:1005:19)
      at require (node:internal/modules/cjs/helpers:102:18)
      at Object.<anonymous> (/redacted-my-service/node_modules/serverless-plugin-datadog/dist/src/index.js:48:35)
      at Module._compile (node:internal/modules/cjs/loader:1101:14)
      at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
      at Module.load (node:internal/modules/cjs/loader:981:32)
      at Function.Module._load (node:internal/modules/cjs/loader:822:12)
      at Module.require (node:internal/modules/cjs/loader:1005:19)
      at require (node:internal/modules/cjs/helpers:102:18)
      at requireServicePlugin (/home/gs/.nvm/versions/node/v16.13.0/lib/node_modules/serverless/lib/classes/PluginManager.js:34:12)
      at /home/gs/.nvm/versions/node/v16.13.0/lib/node_modules/serverless/lib/classes/PluginManager.js:181:22
      at Array.map (<anonymous>)
      at PluginManager.resolveServicePlugins (/home/gs/.nvm/versions/node/v16.13.0/lib/node_modules/serverless/lib/classes/PluginManager.js:178:10)
      at PluginManager.loadAllPlugins (/home/gs/.nvm/versions/node/v16.13.0/lib/node_modules/serverless/lib/classes/PluginManager.js:161:10)
      at Serverless.init (/home/gs/.nvm/versions/node/v16.13.0/lib/node_modules/serverless/lib/Serverless.js:213:30)
      at async /home/gs/.nvm/versions/node/v16.13.0/lib/node_modules/serverless/scripts/serverless.js:585:7

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
```

**Comment by DarcyRaynerDD** [comment]
Hi @gs11 , I checked our yarn.lock file, and couldn't find any mention of axios in that list. If you remove serverless-plugin-datadog, does the error goes away?

**Comment by DarcyRaynerDD** [comment]
Ahh, my mistake. I think I was looking at the wrong yarn.lock. We will take a look at this today.

**Comment by IvanTopolcic** [comment]
Could you please update to v3.5.3 and let me know if the issue is fixed for you?

**Comment by gs11** [comment]
> Could you please update to v3.5.3 and let me know if the issue is fixed for you?

Verified OK, thanks for the quick fix!
