### ISSUE TITLE
Prettier missing as runtime dependency

### ISSUE THREAD

**Issue by dangothemango** [DataDog/serverless-plugin-datadog#369]
## Expected Behavior

Prettier listed as dependency for production npm install

## Actual Behavior

Prettier is only listed as a dev dependency

## Steps to Reproduce the Problem

  1. Update to 5.22.0
  2. Run serverless deploy

## Specifications

  - Datadog Serverless Plugin version: 5.22.0
  - Change: https://github.com/DataDog/serverless-plugin-datadog/compare/v5.21.0...v5.22.0#diff-3b62155f0d03dfb6ac564b6a703b6221a1684e32dd11fa17832600a9165db9bcR4
  
## Stacktrace
  
  ```
Environment: linux, node 16.14.2, framework 3.10.0 (local), plugin 6.2.3, SDK 4.3.2
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues
Error:
Error: Cannot find module 'prettier'

    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/builds/services/learning-portal/node_modules/serverless-plugin-datadog/dist/src/forwarder.js:13:20)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/builds/services/learning-portal/node_modules/serverless-plugin-datadog/dist/src/index.js:41:21)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at module.exports (/builds/services/learning-portal/node_modules/serverless/lib/utils/import-module.js:5:12)
  ```

**Comment by EduardoToledo** [comment]
I can confirm this. For fix install `prettier` package manually

**Comment by dangothemango** [comment]
https://github.com/DataDog/serverless-plugin-datadog/pull/370

**Comment by kimi-p** [comment]
Hi @dangothemango @EduardoToledo , thank you for flagging this issue to us. A fix is released in the latest version: https://github.com/DataDog/serverless-plugin-datadog/releases/tag/v5.23.0
Please let us know if you have any questions!
