### ISSUE TITLE
Datadog instrumentations crashing with aws sdk

### ISSUE THREAD

**Issue by arantesxyz** [DataDog/serverless-plugin-datadog#394]
## Expected Behavior
It should not crash the lambda function and send logs to datadog.

## Actual Behavior
I'm receiving the logs normally, but for some reason my lambda function is crashing with the error in the stacktrace area bellow
Yes, we are using the new aws-sdk in our project, would that conflict with the package inside datadog layer?

## Specifications

  - Datadog Serverless Plugin version: 
![image](https://github.com/DataDog/serverless-plugin-datadog/assets/42740492/fd110d85-bd1c-4bc8-a125-d45d4be1bedf)

  - Lambda function runtime (Python 3.7, Node 10, etc.): Node 16
  
## Stacktrace
  
```
2023-05-29T16:08:05.585Z	b1d56547-7f85-4000-bfd4-c4c11ef18299	INFO	[dd.trace_id=**CONFIDENTIAL** dd.span_id=**CONFIDENTIAL**] HttpController:**CONFIDENTIAL** -  TypeError: this.config.region is not a function
    at /opt/nodejs/node_modules/dd-trace/packages/datadog-instrumentations/src/aws-sdk.js:72:19
    at exports.AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at SQS.send (/opt/nodejs/node_modules/dd-trace/packages/datadog-instrumentations/src/aws-sdk.js:63:20)
    at SQS.methodImpl [as sendMessage] (/var/task/node_modules/@aws-sdk/smithy-client/dist-cjs/create-aggregated-client.js:18:29)
    at SQSSender.sendMessage (/var/task/services/SQSSender.js:11:26)
    at ExecutionService.confirmation (/var/task/services/ExecutionService.js:261:30)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async HttpController.pacs002 (/var/task/controllers/http.js:187:7)
    at async exports.main (/var/task/index.js:45:26)
```

**Comment by tianchu** [comment]
@arantesxyz It seems that the error is from https://github.com/DataDog/dd-trace-js/blob/master/packages/datadog-instrumentations/src/aws-sdk.js#L72. Do you mind filing an issue in that repo as well and link them up?

BTW, any chance you could reproduce this in a minimal app?

**Comment by astuyve** [comment]
Closing this as we haven't heard back for several weeks. Please feel free to re-open with more information if you're still experiencing this issue.

Thanks!
