### ISSUE TITLE
502 Error When I make requests after updating this plugin

### ISSUE THREAD

**Issue by nhorvath-bowery** [DataDog/serverless-plugin-datadog#410]
## Expected Behavior
No errors. Versions below 5.36.0 work correctly.

## Actual Behavior
502 Errors

## Steps to Reproduce the Problem

  1. Use v5.36.0 or v5.37.0 with node 18 serverless lambda
  1. Make a http request

## Specifications

  - Serverless Framework version: 3.33
  - Datadog Serverless Plugin version: 5.36.0, 5.37.0
  - Lambda function runtime (Python 3.7, Node 10, etc.): node 18
  
## Stacktrace
  
  ```
2023-07-14T14:24:17.488Z 31601122-f79a-4ad5-b997-b94781a0a1f6 ERROR Invoke Error { "errorType": "TypeError", "errorMessage": "Cannot read properties of undefined (reading 'then')", "stack": [ "TypeError: Cannot read properties of undefined (reading 'then')", " at /opt/nodejs/node_modules/dd-trace/packages/dd-trace/src/lambda/handler.js:89:43", " at /opt/nodejs/node_modules/datadog-lambda-js/utils/handler.js:166:25", " at /opt/nodejs/node_modules/datadog-lambda-js/index.js:223:70", " at step (/opt/nodejs/node_modules/datadog-lambda-js/index.js:44:23)", " at Object.next (/opt/nodejs/node_modules/datadog-lambda-js/index.js:25:53)", " at /opt/nodejs/node_modules/datadog-lambda-js/index.js:19:71", " at new Promise (<anonymous>)", " at __awaiter (/opt/nodejs/node_modules/datadog-lambda-js/index.js:15:12)", " at traceListenerOnWrap (/opt/nodejs/node_modules/datadog-lambda-js/index.js:200:36)", " at /opt/nodejs/node_modules/dd-trace/packages/dd-trace/src/tracer.js:103:56" ] }
  ```

Downgrading to 5.35.0 resolves the issue. I was on 5.20.0 prior to upgrading. 5.30.0 also worked when I was seeing how far I could go before it broke.

**Comment by astuyve** [comment]
Hey there,  thanks for reaching out!

I'm working on a ticket [right now](https://github.com/DataDog/datadog-lambda-js/issues/404), seems these are the same?

Thanks again!
AJ

**Comment by astuyve** [comment]
It'd be super helpful if you could share a small example of your use case!
I believe I have a fix but I'd really love to double check it against your example before rolling it out.

Thank you!

**Comment by astuyve** [comment]
This should be fixed in 5.39.0!
