### ISSUE TITLE
ENOENT: no such file or directory, stat '/var/runtime/node_modules/aws-sdk/node_modules/aws-sdk/package.json

### ISSUE THREAD

**Issue by bryantbiggs** [DataDog/serverless-plugin-datadog#60]
## Expected Behavior

Traces and logs are error free

## Actual Behavior

The following errors are showing up in our logs:

```json
			{
                "trace_id": "2335ba9203685fb4",
                "span_id": "5ed4b2a01489dbfb",
                "parent_id": "2335ba9203685fb4",
                "name": "fs.operation",
                "resource": "statSync",
                "error": 0,
                "meta": {
                    "error.msg": "ENOENT: no such file or directory, stat '/var/runtime/node_modules/aws-sdk/node_modules/aws-sdk/package.json'",
                    "error.type": "Error",
                    "error.stack": "Error: ENOENT: no such file or directory, stat '/var/runtime/node_modules/aws-sdk/node_modules/aws-sdk/package.json'\n    at Object.statSync (fs.js:1009:3)\n    at /opt/nodejs/node_modules/dd-trace/packages/dd-trace/src/tracer.js:93:53\n    at /opt/nodejs/node_modules/dd-trace/packages/dd-trace/src/tracer.js:45:56\n    at Scope._activate (/opt/nodejs/node_modules/dd-trace/packages/dd-trace/src/scope/async_hooks.js:53:14)\n    at Scope.activate (/opt/nodejs/node_modules/dd-trace/packages/dd-trace/src/scope/base.js:12:19)\n    at DatadogTracer.trace (/opt/nodejs/node_modules/dd-trace/packages/dd-trace/src/tracer.js:45:35)\n    at Object.statSync (/opt/nodejs/node_modules/dd-trace/packages/dd-trace/src/tracer.js:93:23)\n    at isFile (/opt/nodejs/node_modules/resolve/lib/sync.js:10:23)\n    at loadAsDirectorySync (/opt/nodejs/node_modules/resolve/lib/sync.js:137:13)\n    at loadNodeModulesSync (/opt/nodejs/node_modules/resolve/lib/sync.js:178:25)",
                    "_dd.origin": "lambda",
                    "service": "repro-dev-auth-api",
                    "component": "fs",
                    "span.kind": "internal",
                    "file.path": "/var/runtime/node_modules/aws-sdk/node_modules"
                },
                "metrics": {
                    "_sample_rate": 1,
                    "_sampling_priority_v1": 1
                },
                "start": 1597448244683117300,
                "duration": 5001709,
                "service": "repro-dev-auth-api-fs"
            },
            {
                "trace_id": "2335ba9203685fb4",
                "span_id": "598947ec0fa2f3c4",
                "parent_id": "2335ba9203685fb4",
                "name": "fs.operation",
                "resource": "statSync",
                "error": 0,
                "meta": {
                    "error.msg": "ENOENT: no such file or directory, stat '/var/runtime/node_modules/aws-sdk/node_modules/aws-sdk/package.json'",
                    "error.type": "Error",
                    "error.stack": "Error: ENOENT: no such file or directory, stat '/var/runtime/node_modules/aws-sdk/node_modules/aws-sdk/package.json'\n    at Object.statSync (fs.js:1009:3)\n    at /opt/nodejs/node_modules/dd-trace/packages/dd-trace/src/tracer.js:93:53\n    at /opt/nodejs/node_modules/dd-trace/packages/dd-trace/src/tracer.js:45:56\n    at Scope._activate (/opt/nodejs/node_modules/dd-trace/packages/dd-trace/src/scope/async_hooks.js:53:14)\n    at Scope.activate (/opt/nodejs/node_modules/dd-trace/packages/dd-trace/src/scope/base.js:12:19)\n    at DatadogTracer.trace (/opt/nodejs/node_modules/dd-trace/packages/dd-trace/src/tracer.js:45:35)\n    at Object.statSync (/opt/nodejs/node_modules/dd-trace/packages/dd-trace/src/tracer.js:93:23)\n    at isFile (/opt/nodejs/node_modules/resolve/lib/sync.js:10:23)\n    at loadpkg (/opt/nodejs/node_modules/resolve/lib/sync.js:117:14)\n    at loadAsFileSync (/opt/nodejs/node_modules/resolve/lib/sync.js:86:19)",
                    "_dd.origin": "lambda",
                    "service": "repro-dev-auth-api",
                    "component": "fs",
                    "span.kind": "internal",
                    "file.path": "/var/runtime/node_modules/aws-sdk/node_modules"
                },
                "metrics": {
                    "_sample_rate": 1,
                    "_sampling_priority_v1": 1
                },
                "start": 1597448244688188400,
                "duration": 311768,
                "service": "repro-dev-auth-api-fs"
            },
```

and

```json
			{
                "trace_id": "7b691e3bf3c8a9be",
                "span_id": "5d5e282f55a4c54f",
                "parent_id": "3d4de664637c2c43",
                "name": "fs.operation",
                "resource": "openSync",
                "error": 0,
                "meta": {
                    "error.msg": "ENOENT: no such file or directory, open '/home/sbx_user1051/.aws/config'",
                    "error.type": "Error",
                    "error.stack": "Error: ENOENT: no such file or directory, open '/home/sbx_user1051/.aws/config'\n    at Object.openSync (fs.js:458:3)\n    at /opt/nodejs/node_modules/dd-trace/packages/dd-trace/src/tracer.js:93:53\n    at /opt/nodejs/node_modules/dd-trace/packages/dd-trace/src/tracer.js:45:56\n    at Scope._activate (/opt/nodejs/node_modules/dd-trace/packages/dd-trace/src/scope/async_hooks.js:53:14)\n    at Scope.activate (/opt/nodejs/node_modules/dd-trace/packages/dd-trace/src/scope/base.js:12:19)\n    at DatadogTracer.trace (/opt/nodejs/node_modules/dd-trace/packages/dd-trace/src/tracer.js:45:35)\n    at Object.openSync (/opt/nodejs/node_modules/dd-trace/packages/dd-trace/src/tracer.js:93:23)\n    at Object.readFileSync (fs.js:360:35)\n    at /opt/nodejs/node_modules/dd-trace/packages/dd-trace/src/tracer.js:93:53\n    at /opt/nodejs/node_modules/dd-trace/packages/dd-trace/src/tracer.js:45:56",
                    "_dd.origin": "lambda",
                    "service": "repro-dev-auth-api",
                    "component": "fs",
                    "span.kind": "internal",
                    "file.path": "/home/sbx_user1051/.aws/config",
                    "file.flag": "r"
                },
                "metrics": {
                    "_sample_rate": 1,
                    "_sampling_priority_v1": 1
                },
                "start": 1597447653414957800,
                "duration": 355469,
                "service": "repro-dev-auth-api-fs"
            },
            {
                "trace_id": "7b691e3bf3c8a9be",
                "span_id": "3d4de664637c2c43",
                "parent_id": "280b566833b63848",
                "name": "fs.operation",
                "resource": "readFileSync",
                "error": 0,
                "meta": {
                    "error.msg": "ENOENT: no such file or directory, open '/home/sbx_user1051/.aws/config'",
                    "error.type": "Error",
                    "error.stack": "Error: ENOENT: no such file or directory, open '/home/sbx_user1051/.aws/config'\n    at Object.openSync (fs.js:458:3)\n    at /opt/nodejs/node_modules/dd-trace/packages/dd-trace/src/tracer.js:93:53\n    at /opt/nodejs/node_modules/dd-trace/packages/dd-trace/src/tracer.js:45:56\n    at Scope._activate (/opt/nodejs/node_modules/dd-trace/packages/dd-trace/src/scope/async_hooks.js:53:14)\n    at Scope.activate (/opt/nodejs/node_modules/dd-trace/packages/dd-trace/src/scope/base.js:12:19)\n    at DatadogTracer.trace (/opt/nodejs/node_modules/dd-trace/packages/dd-trace/src/tracer.js:45:35)\n    at Object.openSync (/opt/nodejs/node_modules/dd-trace/packages/dd-trace/src/tracer.js:93:23)\n    at Object.readFileSync (fs.js:360:35)\n    at /opt/nodejs/node_modules/dd-trace/packages/dd-trace/src/tracer.js:93:53\n    at /opt/nodejs/node_modules/dd-trace/packages/dd-trace/src/tracer.js:45:56",
                    "_dd.origin": "lambda",
                    "service": "repro-dev-auth-api",
                    "component": "fs",
                    "span.kind": "internal",
                    "file.path": "/home/sbx_user1051/.aws/config",
                    "file.flag": "r"
                },
                "metrics": {
                    "_sample_rate": 1,
                    "_sampling_priority_v1": 1
                },
                "start": 1597447653414909200,
                "duration": 424072,
                "service": "repro-dev-auth-api-fs"
            },
```

## Steps to Reproduce the Problem

Please see the reproduction code/project [here](https://github.com/clowdhaus/dogged-params):
1. Clone project
2. `yarn install`
3. `sls deploy`
4. Create any test payload for the lambda function, even `{}` works
5. Manually invoke the function and inspect the logs 

## Specifications

  - Serverless Framework version: 1.78.1
  - Datadog Serverless Plugin version: 2.1.0 (note this shows up as early as v0.25.0 of the plugin)
  - Lambda function runtime (Python 3.7, Node 10, etc.): Node 12
  
## Stacktrace
  
See above or log output from repro steps

**Comment by tianchu** [comment]
@bryantbiggs thanks for the report! This is known issue due to how AWS SDK uses `fs` to look up files, it basically try to open the file if not catch the exception. Because `fs` does not know the SDK catches the exception, to `fs` they are  indeed exceptions. 

It is very confusing, so there was a change made to the `ddtrace` library to not display them as errors (hence `"error": 0`) but still capture them. Do you still see them as errors in UI?

If you don't like them showing up in your logs, set env variable `DD_TRACE_DISABLED_PLUGINS` with value `fs`, which would disable the tracer's integration with `fs` and those spans.

**Comment by bryantbiggs** [comment]
my apologies @tianchu, I haven't had time to go back and check. I'll reach back out after I've done some more testing and checking the UI, what I was seeing was mostly just in the logs that were generated
