### ISSUE TITLE
Cannot Read Property Resources

### ISSUE THREAD

**Issue by dtothefp** [DataDog/serverless-plugin-datadog#63]
## Expected Behavior
Running `serverless deploy --function <my_function>` should work just the same as running `serverless deploy` for all functions.

## Actual Behavior
Deploying a single function fails `serverless deploy --function <my_function>`

Additionally I see this error if I do a local invoke

```
serverless invoke local -f <my_function> -p ./event.json
```

Is there a way to disable this plugin for these types of invocations / deploys?

## Steps to Reproduce the Problem

  1. deploy all your functions by running `serverless deploy`
  2. now try to deploy a single function `serverless deploy <my_function>

## Specifications

  - Serverless Framework version: 1.77.1
  - Datadog Serverless Plugin version: 2.2.1
  - Lambda function runtime (Python 3.7, Node 10, etc.): nodejs12.x
  
## Stacktrace
  
```
  TypeError: Cannot read property 'Resources' of undefined
      at Object.<anonymous> (/Users/davidfox-powell/dev/good-rx/cross-origin-ab-test/node_modules/serverless-plugin-datadog/src/forwarder.ts:31:69)
      at Generator.next (<anonymous>)
      at /Users/davidfox-powell/dev/good-rx/cross-origin-ab-test/node_modules/serverless-plugin-datadog/dist/forwarder.js:8:71
      at new Promise (<anonymous>)
      at __awaiter (/Users/davidfox-powell/dev/good-rx/cross-origin-ab-test/node_modules/serverless-plugin-datadog/dist/forwarder.js:4:12)
      at Object.addCloudWatchForwarderSubscriptions (/Users/davidfox-powell/dev/good-rx/cross-origin-ab-test/node_modules/serverless-plugin-datadog/dist/forwarder.js:19:12)
      at ServerlessPlugin.<anonymous> (/Users/davidfox-powell/dev/good-rx/cross-origin-ab-test/node_modules/serverless-plugin-datadog/src/index.ts:91:28)
      at Generator.next (<anonymous>)
      at /Users/davidfox-powell/dev/good-rx/cross-origin-ab-test/node_modules/serverless-plugin-datadog/dist/index.js:34:71
      at new Promise (<anonymous>)
      at __awaiter (/Users/davidfox-powell/dev/good-rx/cross-origin-ab-test/node_modules/serverless-plugin-datadog/dist/index.js:30:12)
      at ServerlessPlugin.afterPackageFunction (/Users/davidfox-powell/dev/good-rx/cross-origin-ab-test/node_modules/serverless-plugin-datadog/dist/index.js:110:16)
      at /Users/davidfox-powell/dev/good-rx/cross-origin-ab-test/node_modules/serverless/lib/classes/PluginManager.js:483:55
      at tryCatcher (/Users/davidfox-powell/dev/good-rx/cross-origin-ab-test/node_modules/bluebird/js/release/util.js:16:23)
      at Object.gotValue (/Users/davidfox-powell/dev/good-rx/cross-origin-ab-test/node_modules/bluebird/js/release/reduce.js:168:18)
      at Object.gotAccum (/Users/davidfox-powell/dev/good-rx/cross-origin-ab-test/node_modules/bluebird/js/release/reduce.js:155:25)
      at Object.tryCatcher (/Users/davidfox-powell/dev/good-rx/cross-origin-ab-test/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/Users/davidfox-powell/dev/good-rx/cross-origin-ab-test/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/Users/davidfox-powell/dev/good-rx/cross-origin-ab-test/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (/Users/davidfox-powell/dev/good-rx/cross-origin-ab-test/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/Users/davidfox-powell/dev/good-rx/cross-origin-ab-test/node_modules/bluebird/js/release/promise.js:729:18)
      at _drainQueueStep (/Users/davidfox-powell/dev/good-rx/cross-origin-ab-test/node_modules/bluebird/js/release/async.js:93:12)
      at _drainQueue (/Users/davidfox-powell/dev/good-rx/cross-origin-ab-test/node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (/Users/davidfox-powell/dev/good-rx/cross-origin-ab-test/node_modules/bluebird/js/release/async.js:102:5)
      at Immediate.Async.drainQueues (/Users/davidfox-powell/dev/good-rx/cross-origin-ab-test/node_modules/bluebird/js/release/async.js:15:14)
      at processImmediate (internal/timers.js:456:21)
      at process.topLevelDomainCallback (domain.js:137:15)
```

**Comment by DarcyRaynerDD** [comment]
Hey @dtothefp, thanks for the bug report. I'm adding a ticket to our internal board for this issue. We'll update here once we have a fix available.

**Comment by jspreddy** [comment]
I am having the same exact issue with invoking the functions locally.
```
TypeError: Cannot read property 'Resources' of undefined
```
Is there a work around for this?

I know that commenting out the plugin from the `serverless.yml` works for me locally.

**Comment by Czechh** [comment]
@dtothefp @jspreddy bumping last message from my teammate.

**Comment by tianchu** [comment]
Closing the issue due to inactivity.
