### ISSUE TITLE
The Datadog-Node10-x:29 lambda layer might not have the right access policy

### ISSUE THREAD

**Issue by dls314** [DataDog/serverless-plugin-datadog#65]
## Expected Behavior

Upgrading to serverless-plugin-datadog 2.2.2 works

## Actual Behavior

It does not work and the error I get contains this information (some account numbers, guids and timestamps elided)

```
ServerlessError: An error occurred: ProviderLambdaFunction - User: arn:aws:sts::012345678901:assumed-role/admin/aws-sdk-js-1598381214288 is not authorized to perform: lambda:GetLayerVersion on resource: arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Node10-x:29 (Service: AWSLambdaInternal; Status Code: 403; Error Code: AccessDeniedException; Request ID: 00000000-0000-0000-0000-000000000000; Proxy: null).
```

## Steps to Reproduce the Problem

  1. Upgrade a project to use serverless-plugin-datadog 2.2.2 and try to deploy with my AWS credentials (sorry, but honest)

## Specifications

  - Serverless Framework version: "serverless": "^1.79.0",
  - Datadog Serverless Plugin version: "serverless-plugin-datadog": "^2.2.2",
  - Lambda function runtime (Python 3.7, Node 10, etc.): 10
  
## Stacktrace
Some account numbers, guids, timestamps, and paths elided

  ```
ServerlessError: An error occurred: ProviderLambdaFunction - User: arn:aws:sts::012345678901:assumed-role/admin/aws-sdk-js-1598381214288 is not authorized to perform: lambda:GetLayerVersion on resource: arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Node10-x:29 (Service: AWSLambdaInternal; Status Code: 403; Error Code: AccessDeniedException; Request ID: 00000000-0000-0000-0000-000000000000; Proxy: null).
      at C:\service\node_modules\serverless\lib\plugins\aws\lib\monitorStack.js:125:33
  From previous event:
      at AwsDeploy.monitorStack (C:\service\node_modules\serverless\lib\plugins\aws\lib\monitorStack.js:28:12)  
      at C:\service\node_modules\serverless\lib\plugins\aws\lib\updateStack.js:134:28
  From previous event:
      at AwsDeploy.update (C:\service\node_modules\serverless\lib\plugins\aws\lib\updateStack.js:134:8)
  From previous event:
      at AwsDeploy.<anonymous> (C:\service\node_modules\serverless\lib\plugins\aws\lib\updateStack.js:148:35)   
  From previous event:
      at AwsDeploy.updateStack (C:\service\node_modules\serverless\lib\plugins\aws\lib\updateStack.js:144:33)   
  From previous event:
      at AwsDeploy.<anonymous> (C:\service\node_modules\serverless\lib\plugins\aws\deploy\index.js:127:39)      
  From previous event:
      at Object.aws:deploy:deploy:updateStack [as hook] (C:\service\node_modules\serverless\lib\plugins\aws\deploy\index.js:123:30)
      at C:\service\node_modules\serverless\lib\classes\PluginManager.js:489:55
  From previous event:
      at PluginManager.invoke (C:\service\node_modules\serverless\lib\classes\PluginManager.js:489:22)
      at PluginManager.spawn (C:\service\node_modules\serverless\lib\classes\PluginManager.js:509:17)
      at AwsDeploy.<anonymous> (C:\service\node_modules\serverless\lib\plugins\aws\deploy\index.js:93:48)       
  From previous event:
      at Object.deploy:deploy [as hook] (C:\service\node_modules\serverless\lib\plugins\aws\deploy\index.js:89:30)
      at C:\service\node_modules\serverless\lib\classes\PluginManager.js:489:55
  From previous event:
      at PluginManager.invoke (C:\service\node_modules\serverless\lib\classes\PluginManager.js:489:22)
      at C:\service\node_modules\serverless\lib\classes\PluginManager.js:524:24
  From previous event:
      at PluginManager.run (C:\service\node_modules\serverless\lib\classes\PluginManager.js:524:8)
      at C:\service\node_modules\serverless\lib\Serverless.js:136:33
  From previous event:
      at Serverless.run (C:\service\node_modules\serverless\lib\Serverless.js:123:74)
      at C:\service\node_modules\serverless\scripts\serverless.js:54:26
      at processImmediate (internal/timers.js:456:21)
      at process.topLevelDomainCallback (domain.js:137:15)
  From previous event:
      at Object.<anonymous> (C:\service\node_modules\serverless\scripts\serverless.js:54:4)
      at Module._compile (internal/modules/cjs/loader.js:1133:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
      at Module.load (internal/modules/cjs/loader.js:977:32)
      at Function.Module._load (internal/modules/cjs/loader.js:877:14)
      at Module.require (internal/modules/cjs/loader.js:1019:19)
      at require (internal/modules/cjs/helpers.js:77:18)
      at Object.<anonymous> (C:\service\node_modules\serverless\bin\serverless.js:41:1)
      at Module._compile (internal/modules/cjs/loader.js:1133:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
      at Module.load (internal/modules/cjs/loader.js:977:32)
      at Function.Module._load (internal/modules/cjs/loader.js:877:14)
      at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
      at internal/main/run_main_module.js:18:47
  ```

**Comment by hghotra** [comment]
Hi @dls314 , I reset the access policy for the lambda layer - give it another shot and let's see if that did the trick.

**Comment by dls314** [comment]
Downgrading to 2.2.1 resolves the issue for me.

**Comment by dls314** [comment]
> Hi @dls314 , I reset the access policy for the lambda layer - give it another shot and let's see if that did the trick.

👍 Will try

**Comment by dls314** [comment]
That fixed it. Thanks!
